spring:
  data:
    mongodb:
      uri: mongodb+srv://Mryankeecj23:Lugnuts1234@users.udydyvc.mongodb.net/UserInfo?retryWrites=true&w=majority&appName=users
      

  
token:
  expirationms: 36000
  secret:
    key: "daef29f56ce437986fd39140c358bf9f001f04683d59c1ae667a2a776d874d8d"
